services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString
      - key: EMAIL_HOST_USER
        value: neupaneananda.10@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: jbisxyiktklnkdtc
      - key: PYTHON_VERSION
        value: 3.11

databases:
  - name: django-db
    plan: free
