# Generated by Django 5.1.4 on 2025-04-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='goal_duration',
            field=models.CharField(blank=True, choices=[('1 month', '1 month'), ('2 months', '2 months'), ('3 months', '3 months'), ('4 months', '4 months'), ('5 months', '5 months'), ('6 months', '6 months'), ('7 months', '7 months'), ('8 months', '8 months'), ('9 months', '9 months'), ('10 months', '10 months'), ('11 months', '11 months'), ('12 months', '12 months')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='goal_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
