# Generated by Django 5.1.4 on 2025-02-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='exercise_date',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='exercise_name',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='user',
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='equipment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='gif_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='secondary_muscles',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='target',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='body_part',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
