# Generated by Django 5.1.4 on 2025-04-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0002_customuser_goal_duration_customuser_goal_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='secondary',
            field=models.CharField(blank=True, null=True),
        ),
    ]
