# Generated by Django 5.1.4 on 2025-02-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0003_remove_workoutexercise_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='exercise_id',
            field=models.IntegerField(default=1),
        ),
    ]
