# Generated by Django 5.1.4 on 2025-02-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0003_otp_workout_workoutexercise_exerciseperformance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_created_at',
        ),
    ]
