# Generated by Django 5.1.4 on 2025-04-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0003_exercise_secondary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='secondary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
