# Generated by Django 5.1.4 on 2025-02-17 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0004_alter_workoutexercise_exercise_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutexercise',
            old_name='exercise_id',
            new_name='workout_exercise_id',
        ),
    ]
