# Generated by Django 5.1.4 on 2025-02-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0005_rename_exercise_id_workoutexercise_workout_exercise_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='total_calories',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
