# Generated by Django 5.1.4 on 2025-04-12 02:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0006_remove_customuser_otp_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_calories', models.IntegerField(default=0)),
                ('total_carbs', models.FloatField(default=0)),
                ('total_proteins', models.FloatField(default=0)),
                ('total_fats', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack'), ('DESSERT', 'Dessert')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('calories', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('carbohydrates', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('proteins', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fats', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('consumed', models.BooleanField(default=False)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='FitHub.dailymealplan')),
            ],
            options={
                'ordering': ['meal_type', 'reminder_time'],
            },
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(max_length=50)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='FitHub.meal')),
            ],
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['daily_plan', 'meal_type'], name='FitHub_meal_daily_p_70d531_idx'),
        ),
    ]
