# Generated by Django 5.1.4 on 2025-02-19 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0006_alter_workoutexercise_total_calories'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_libraries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLibraryExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_exercise_id', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('body_part', models.CharField(max_length=100, null=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='FitHub.workoutlibrary')),
            ],
        ),
    ]
