# Generated by Django 5.1.4 on 2025-04-12 06:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0007_dailymealplan_meal_mealingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealingredient',
            name='meal',
        ),
        migrations.AlterModelOptions(
            name='dailymealplan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='meal',
            name='FitHub_meal_daily_p_70d531_idx',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='reminder_time',
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='dietary_restrictions',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meal',
            name='dietary_restrictions',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='dailymealplan',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailymealplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbohydrates',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fats',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='meal',
            name='proteins',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='MealIngredient',
        ),
    ]
