# Generated by Django 5.1.4 on 2025-02-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0007_customuser_otp_created_at_customuser_reset_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='custom_workout_name',
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
