# Generated by Django 5.1.4 on 2025-02-19 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0007_workoutlibrary_workoutlibraryexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workout_library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FitHub.workoutlibrary'),
        ),
    ]
