# Generated by Django 5.1.4 on 2025-02-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0007_customuser_otp_created_at_customuser_reset_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('force', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('mechanic', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('primary_muscles', models.JSONField()),
                ('secondary_muscles', models.JSONField()),
                ('instructions', models.JSONField()),
                ('images', models.JSONField()),
            ],
        ),
    ]
