# Generated by Django 5.1.4 on 2025-02-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0008_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='mechanic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
