# Generated by Django 5.1.4 on 2025-03-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0009_customuser_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_photo',
        ),
    ]
