# Generated by Django 5.1.4 on 2025-02-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0009_alter_exercise_mechanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
