# Generated by Django 5.1.4 on 2025-04-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0010_remove_meal_daily_plan_remove_mealingredient_meal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='dietary_restriction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
