# Generated by Django 5.1.4 on 2025-02-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0010_alter_exercise_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='force',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
