# Generated by Django 5.1.4 on 2025-04-13 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0011_alter_mealplan_dietary_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
