# Generated by Django 5.1.4 on 2025-04-21 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0012_customuser_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='body_part',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='workout_exercise_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_entries', to='FitHub.exercise'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='goal_duration',
            field=models.CharField(blank=True, choices=[('1 month', '1 month'), ('2 month', '2 month'), ('3 month', '3 month'), ('4 month', '4 month'), ('5 month', '5 month'), ('6 month', '6 month'), ('7 month', '7 month'), ('8 month', '8 month'), ('9 month', '9 month'), ('10 month', '10 month'), ('11 month', '11 month'), ('12 month', '12 month')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='total_calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='FitHub.workout'),
        ),
    ]
