# Generated by Django 5.1.4 on 2025-04-04 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0013_favoriteexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteexercise',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='favoriteexercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
