# Generated by Django 5.1.4 on 2025-05-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0014_exercisehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='met',
            field=models.FloatField(default=5.0),
        ),
    ]
