# Generated by Django 5.1.4 on 2025-05-23 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHub', '0017_poseestimationsession_posefeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoseExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(default=1)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reps', models.IntegerField(default=1)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('calories_burned', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FitHub.exercise')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pose_set', to='FitHub.poseestimationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pose_exercise_sets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
